export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS";
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES"
export const SORT_BY_POPULATION = "SORT_BY_POPULATION";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";